#!/bin/sh
#
# $NetBSD: rc,v 1.173 2017/03/20 16:02:48 christos Exp $
#

late_divider=/etc/rc.d/FILESYSTEMS

echo "/etc/rc:"

export HOME=/
export PATH=/sbin:/bin:/usr/sbin:/usr/bin
umask 022

#
# Completely ignore INT and QUIT at the outer level.  The rc_real_work()
# function should do something different.
#
trap '' INT QUIT

#
# Get a list of all rc.d scripts, and use rcorder to choose
# what order to execute them.
#
# For testing, allow RC_FILES_OVERRIDE from the environment to
# override this.
#
scripts=$(for rcd in ${rc_directories:-/etc/rc.d}; do
	test -d ${rcd} && echo ${rcd}/*;
done)
files=$(rcorder -s nostart ${rc_rcorder_flags} ${scripts})

if [ -n "${RC_FILES_OVERRIDE}" ]; then
	files="${RC_FILES_OVERRIDE}"
fi

echo "Running early startup scripts"

#
# Run the scripts in order.
#
for _rc_elem in $files; do
	[ $_rc_elem = $late_divider ] && break
	echo "$_rc_elem"
	$_rc_elem faststart
done

printf "Starting InitWare manager"
export LD_LIBRARY_PATH=/usr/local/lib:/usr/pkg/lib
exec /usr/local/libexec/InitWare/svc.managerd --system  
