.Dd April 8, 2021
.Dt INDEX 7

.Sh NAME
.Nm index
.Nd index to the InitWare Reference Library

.Sh DESCRIPTION

This is the index to the InitWare Reference Library, the authoritative reference
on the operation of the InitWare Suite of Middleware.

.Ss Miscellaneous Information Manual

.Bl -tag
.It Xr iw_rcng 7
InitWare's Mewburn RC compatibility subsystem.
.El

.Ss System Manager's Manual

.Bl -tag
.It Xr iw.manager 8
The InitWare manager daemon.
.El
