BEGIN TRANSACTION;

CREATE TABLE "Events" (
	"EventID"	INTEGER NOT NULL UNIQUE,
	"__REALTIME_TIMESTAMP"	INTEGER NOT NULL,
	"__MONOTONIC_TIMESTAMP"	INTEGER NOT NULL,
	"_SYSTEMD_SLICE"	TEXT,
	"_SYSTEMD_UNIT"	TEXT,
	"_SYSTEMD_USER_UNIT"	TEXT,
	"_SYSTEMD_USER_SLICE"	TEXT,
	"_SYSTEMD_SESSION"	TEXT,
	"_SYSTEMD_OWNER_UID"	TEXT,
	"_PID"	INTEGER,
	"_UID"	INTEGER,
	"_GID"	INTEGER,
	"_COMM"	TEXT,
	"_EXE"	TEXT,
	"_CMDLINE"	TEXT,
	"_SOURCE_REALTIME_TIMESTAMP"	TEXT,
	"_BOOT_ID"	TEXT NOT NULL,
	"_MACHINE_ID"	TEXT NOT NULL,
	"_HOSTNAME"	TEXT NOT NULL,
	"_TRANSPORT"	INTEGER NOT NULL,
	"MESSAGE"	TEXT NOT NULL,
	"MESSAGE_ID"	TEXT,
	"PRIORITY"	INTEGER,
	"SYSLOG_FACILITY"	INTEGER,
	"SYSLOG_IDENTIFIER"	TEXT,
	"EXTRA_FIELDS_JSON" TEXT,
	PRIMARY KEY("EventID")
);

CREATE TABLE "Metadata" (
	"Version"	INTEGER NOT NULL
);

COMMIT;
